package main

// catalog.go — portafolio Colsubsidio Protege para la demo.
//
// GENERADO desde sourceapi.json (portafolio real publicado por Colsubsidio:
// 21 productos, segmentos, coberturas mencionadas y fuentes citadas). No se
// edita a mano: se regenera con scripts/gen_catalog.py.
//
// HONESTIDAD: sourceapi.json NO trae precios — Colsubsidio no los publica, y el
// propio JSON los lista bajo `condiciones_no_publicadas` junto a deducibles,
// topes y sumas aseguradas. Las primas de aquí son ESTIMACIONES DE DEMO y cada
// producto lo declara en metadata_json.price_source. Las coberturas INCLUIDAS
// salen del JSON; las OPCIONALES son añadidos de demo, marcados como tales,
// para que ajustar coberturas tenga un efecto real sobre el precio.

// Coverage es una cobertura de un producto. Included distingue lo que ya trae
// la prima base de lo que el cliente puede añadir pagando PriceDelta más.
type Coverage struct {
	Key        string  `json:"key"`
	Label      string  `json:"label"`
	Included   bool    `json:"included"`
	PriceDelta float64 `json:"price_delta"`
	Source     string  `json:"source"` // portafolio_publicado | estimacion_demo
}

var products = []map[string]interface{}{
	{
		"id": "ef4cc0ae-64af-5c70-a9f7-bfbf7e09b650", "code": "SEGURO_DE_VIDA",
		"name": "Seguro de vida",
		"description": "Respaldo económico para los beneficiarios ante fallecimiento, incapacidad permanente o enfermedades graves.",
		"category": "familia", "active": true, "base_price": 25000.0,
		"coverages": []Coverage{
			{Key: "fallecimiento", Label: "Fallecimiento", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "incapacidad", Label: "Incapacidad permanente", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "proteccion_economica", Label: "Protección económica a beneficiarios", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "asistencia_medica_telefonica", Label: "Asistencia médica telefónica 24/7", Included: false, PriceDelta: 4000, Source: "estimacion_demo"},
			{Key: "auxilio_exequial", Label: "Auxilio exequial complementario", Included: false, PriceDelta: 6000, Source: "estimacion_demo"},
		},
		"metadata_json": map[string]interface{}{
			"segmento": "familia", "subsegmento": "proteccion_personal",
			"modalidad": "individual_familiar", "alianza": "aseguradoras_del_pais",
			"beneficios": []string{"tranquilidad_familiar", "respaldo_financiero"},
			"canales": []string{"pagina_web", "asesoria"},
			"fuentes": []string{"https://www.colsubsidio.com/seguros/familiares/vida", "https://ayuda.colsubsidio.com/que-seguros-asistencias-ofrece-colsubsidio"},
			"price_source": "estimación de demo — Colsubsidio no publica primas (ver condiciones_no_publicadas en sourceapi.json)",
			"condiciones_no_publicadas": []string{"deducibles", "exclusiones", "topes", "periodos_de_carencia", "suma_asegurada"},
		},
		"created_at": "2026-07-25T00:00:00Z", "updated_at": "2026-07-25T00:00:00Z",
	},
	{
		"id": "31beb920-0fed-51ce-b2df-b84a48e19600", "code": "SEGURO_VIDA_Y_AHORRO",
		"name": "Seguro Vida y Ahorro",
		"description": "Combina protección para la familia con acumulación de ahorro a lo largo del tiempo.",
		"category": "familia", "active": true, "base_price": 58000.0,
		"coverages": []Coverage{
			{Key: "proteccion_familiar", Label: "Proteccion familiar", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "ahorro", Label: "Componente de ahorro", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "asistencia_medica_telefonica", Label: "Asistencia médica telefónica 24/7", Included: false, PriceDelta: 4000, Source: "estimacion_demo"},
			{Key: "auxilio_exequial", Label: "Auxilio exequial complementario", Included: false, PriceDelta: 6000, Source: "estimacion_demo"},
		},
		"metadata_json": map[string]interface{}{
			"segmento": "familia", "subsegmento": "proteccion_ahorro",
			"modalidad": "individual", "alianza": "colsubsidio_y_aliados",
			"beneficios": []string{"doble_beneficio", "crecimiento_del_ahorro"},
			"canales": []string{"pagina_web"},
			"fuentes": []string{"https://www.colsubsidio.com/seguros/familiares/vida-ahorro"},
			"price_source": "estimación de demo — Colsubsidio no publica primas (ver condiciones_no_publicadas en sourceapi.json)",
			"condiciones_no_publicadas": []string{"rentabilidad", "plazo", "rescates", "exclusiones", "suma_asegurada"},
		},
		"created_at": "2026-07-25T00:00:00Z", "updated_at": "2026-07-25T00:00:00Z",
	},
	{
		"id": "cd2965eb-1d0b-53a1-a20e-2af4ebf87ac8", "code": "ACCIDENTES_PERSONALES",
		"name": "Accidentes personales",
		"description": "Seguro orientado a eventos accidentales dentro del portafolio familiar.",
		"category": "familia", "active": true, "base_price": 18000.0,
		"coverages": []Coverage{
			{Key: "accidente", Label: "Accidente", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "incapacidad_total_o_permanente", Label: "Incapacidad total o permanente", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "desmembracion_por_accidente", Label: "Desmembracion por accidente", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "asistencia_medica_telefonica", Label: "Asistencia médica telefónica 24/7", Included: false, PriceDelta: 4000, Source: "estimacion_demo"},
			{Key: "auxilio_exequial", Label: "Auxilio exequial complementario", Included: false, PriceDelta: 6000, Source: "estimacion_demo"},
		},
		"metadata_json": map[string]interface{}{
			"segmento": "familia", "subsegmento": "proteccion_personal",
			"modalidad": "individual_familiar", "alianza": "aseguradoras_del_pais",
			"beneficios": []string{"respaldo_economico"},
			"canales": []string{"portafolio_familiar", "tarifas_credito"},
			"fuentes": []string{"https://ayuda.colsubsidio.com/que-seguros-asistencias-ofrece-colsubsidio", "https://cms.colsubsidio.com/sites/default/files/Documentos/colsubsidio/2026/cupo-credito-colsubsidio-carta-tarifas.pdf"},
			"price_source": "estimación de demo — Colsubsidio no publica primas (ver condiciones_no_publicadas en sourceapi.json)",
			"condiciones_no_publicadas": []string{"topes", "deducibles", "exclusiones", "periodos_de_carencia"},
		},
		"created_at": "2026-07-25T00:00:00Z", "updated_at": "2026-07-25T00:00:00Z",
	},
	{
		"id": "e61a75d2-d95a-5566-98ce-f65046a96ad5", "code": "RENTA_POR_HOSPITALIZACI_N",
		"name": "Renta por hospitalización",
		"description": "Producto del portafolio familiar orientado a mitigar impacto económico durante hospitalización.",
		"category": "familia", "active": true, "base_price": 21000.0,
		"coverages": []Coverage{
			{Key: "hospitalizacion", Label: "Hospitalización", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "asistencia_medica_telefonica", Label: "Asistencia médica telefónica 24/7", Included: false, PriceDelta: 4000, Source: "estimacion_demo"},
			{Key: "auxilio_exequial", Label: "Auxilio exequial complementario", Included: false, PriceDelta: 6000, Source: "estimacion_demo"},
		},
		"metadata_json": map[string]interface{}{
			"segmento": "familia", "subsegmento": "proteccion_ingresos",
			"modalidad": "individual", "alianza": "aseguradoras_del_pais",
			"beneficios": []string{"apoyo_financiero_temporal"},
			"canales": []string{"portafolio_familiar"},
			"fuentes": []string{"https://ayuda.colsubsidio.com/que-seguros-asistencias-ofrece-colsubsidio"},
			"price_source": "estimación de demo — Colsubsidio no publica primas (ver condiciones_no_publicadas en sourceapi.json)",
			"condiciones_no_publicadas": []string{"monto_diario", "duracion_maxima", "deducibles", "exclusiones"},
		},
		"created_at": "2026-07-25T00:00:00Z", "updated_at": "2026-07-25T00:00:00Z",
	},
	{
		"id": "7bfc424a-00ac-59b1-bdd3-d0b4fe7afa39", "code": "DIAGN_STICO_POSITIVO_DE_C_NCER",
		"name": "Diagnóstico positivo de cáncer",
		"description": "Cobertura asociada al diagnóstico positivo de cáncer dentro del portafolio familiar.",
		"category": "familia", "active": true, "base_price": 27000.0,
		"coverages": []Coverage{
			{Key: "diagnostico_de_cancer", Label: "Diagnostico de cancer", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "asistencia_medica_telefonica", Label: "Asistencia médica telefónica 24/7", Included: false, PriceDelta: 4000, Source: "estimacion_demo"},
			{Key: "auxilio_exequial", Label: "Auxilio exequial complementario", Included: false, PriceDelta: 6000, Source: "estimacion_demo"},
		},
		"metadata_json": map[string]interface{}{
			"segmento": "familia", "subsegmento": "enfermedades_graves",
			"modalidad": "individual", "alianza": "aseguradoras_del_pais",
			"beneficios": []string{"respaldo_financiero"},
			"canales": []string{"portafolio_familiar"},
			"fuentes": []string{"https://ayuda.colsubsidio.com/que-seguros-asistencias-ofrece-colsubsidio"},
			"price_source": "estimación de demo — Colsubsidio no publica primas (ver condiciones_no_publicadas en sourceapi.json)",
			"condiciones_no_publicadas": []string{"definicion_de_evento", "topes", "periodos_de_carencia", "exclusiones"},
		},
		"created_at": "2026-07-25T00:00:00Z", "updated_at": "2026-07-25T00:00:00Z",
	},
	{
		"id": "78de9b51-29d9-5506-ba6d-d74a4763e3d9", "code": "P_LIZA_DE_SALUD",
		"name": "Póliza de salud",
		"description": "Protección familiar integral enfocada en salud y bienestar.",
		"category": "familia", "active": true, "base_price": 96000.0,
		"coverages": []Coverage{
			{Key: "salud", Label: "Atención en salud", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "atencion_medica", Label: "Atencion medica", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "asistencia_medica_telefonica", Label: "Asistencia médica telefónica 24/7", Included: false, PriceDelta: 4000, Source: "estimacion_demo"},
			{Key: "auxilio_exequial", Label: "Auxilio exequial complementario", Included: false, PriceDelta: 6000, Source: "estimacion_demo"},
		},
		"metadata_json": map[string]interface{}{
			"segmento": "familia", "subsegmento": "salud",
			"modalidad": "familiar", "alianza": "aseguradoras_del_pais",
			"beneficios": []string{"bienestar", "proteccion_familiar"},
			"canales": []string{"pagina_web", "portafolio_familiar"},
			"fuentes": []string{"https://www.colsubsidio.com/seguros/familiares/poliza-salud", "https://ayuda.colsubsidio.com/que-seguros-asistencias-ofrece-colsubsidio"},
			"price_source": "estimación de demo — Colsubsidio no publica primas (ver condiciones_no_publicadas en sourceapi.json)",
			"condiciones_no_publicadas": []string{"red_medica", "topes", "carencias", "exclusiones", "copagos"},
		},
		"created_at": "2026-07-25T00:00:00Z", "updated_at": "2026-07-25T00:00:00Z",
	},
	{
		"id": "a80efc0f-3b48-5e16-a295-c89883ce362d", "code": "EXEQUIAL_FAMILIAR",
		"name": "Exequial familiar",
		"description": "Cobertura para gastos y apoyo en servicios funerarios.",
		"category": "familia", "active": true, "base_price": 16000.0,
		"coverages": []Coverage{
			{Key: "gastos_funerarios", Label: "Gastos funerarios", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "servicios_exequiales", Label: "Servicios exequiales", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "asistencia_medica_telefonica", Label: "Asistencia médica telefónica 24/7", Included: false, PriceDelta: 4000, Source: "estimacion_demo"},
			{Key: "auxilio_exequial", Label: "Auxilio exequial complementario", Included: false, PriceDelta: 6000, Source: "estimacion_demo"},
		},
		"metadata_json": map[string]interface{}{
			"segmento": "familia", "subsegmento": "exequias",
			"modalidad": "familiar", "alianza": "aseguradoras_del_pais",
			"beneficios": []string{"respaldo_en_momentos_criticos"},
			"canales": []string{"portafolio_familiar"},
			"fuentes": []string{"https://ayuda.colsubsidio.com/que-seguros-asistencias-ofrece-colsubsidio", "https://www.colsubsidio.com/seguros/familiares"},
			"price_source": "estimación de demo — Colsubsidio no publica primas (ver condiciones_no_publicadas en sourceapi.json)",
			"condiciones_no_publicadas": []string{"alcance_del_servicio", "topes", "carencias", "cobertura_geografica"},
		},
		"created_at": "2026-07-25T00:00:00Z", "updated_at": "2026-07-25T00:00:00Z",
	},
	{
		"id": "b25c56e5-b406-5609-be1f-d6ea6eda04b2", "code": "SEGURO_DE_MASCOTAS",
		"name": "Seguro de mascotas",
		"description": "Cobertura para proteger a las mascotas dentro del portafolio familiar.",
		"category": "familia", "active": true, "base_price": 22000.0,
		"coverages": []Coverage{
			{Key: "mascotas", Label: "Mascotas", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "asistencia_medica_telefonica", Label: "Asistencia médica telefónica 24/7", Included: false, PriceDelta: 4000, Source: "estimacion_demo"},
			{Key: "auxilio_exequial", Label: "Auxilio exequial complementario", Included: false, PriceDelta: 6000, Source: "estimacion_demo"},
		},
		"metadata_json": map[string]interface{}{
			"segmento": "familia", "subsegmento": "mascotas",
			"modalidad": "individual_familiar", "alianza": "aseguradoras_del_pais",
			"beneficios": []string{"tranquilidad"},
			"canales": []string{"portafolio_familiar", "asistencias"},
			"fuentes": []string{"https://ayuda.colsubsidio.com/que-seguros-asistencias-ofrece-colsubsidio"},
			"price_source": "estimación de demo — Colsubsidio no publica primas (ver condiciones_no_publicadas en sourceapi.json)",
			"condiciones_no_publicadas": []string{"tipos_de_mascotas", "topes", "exclusiones", "edad_minima_maxima"},
		},
		"created_at": "2026-07-25T00:00:00Z", "updated_at": "2026-07-25T00:00:00Z",
	},
	{
		"id": "51e10984-578e-59fd-b68c-d8e26e9bc42a", "code": "TODO_RIESGO_AUTOS_Y_MOTOS",
		"name": "Todo riesgo autos y motos",
		"description": "Protección patrimonial para vehículos particulares.",
		"category": "patrimonio", "active": true, "base_price": 145000.0,
		"coverages": []Coverage{
			{Key: "autos", Label: "Autos", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "motos", Label: "Motos", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "daños_a_terceros", Label: "Daños a terceros", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "robo", Label: "Hurto", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "accidentes", Label: "Accidentes personales", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "asistencia_domiciliaria", Label: "Asistencia domiciliaria (plomería, cerrajería)", Included: false, PriceDelta: 5000, Source: "estimacion_demo"},
			{Key: "contenido_electronico", Label: "Contenido electrónico y tecnología", Included: false, PriceDelta: 7000, Source: "estimacion_demo"},
		},
		"metadata_json": map[string]interface{}{
			"segmento": "patrimonio", "subsegmento": "vehiculos",
			"modalidad": "individual", "alianza": "aseguradoras_del_pais",
			"beneficios": []string{"proteccion_del_vehiculo"},
			"canales": []string{"pagina_web", "patrimonio"},
			"fuentes": []string{"https://ayuda.colsubsidio.com/que-seguros-asistencias-ofrece-colsubsidio", "https://www.colsubsidio.com/seguros/vehiculos/carro"},
			"price_source": "estimación de demo — Colsubsidio no publica primas (ver condiciones_no_publicadas en sourceapi.json)",
			"condiciones_no_publicadas": []string{"deducibles", "vigencia", "coberturas_adicionales", "exclusiones"},
		},
		"created_at": "2026-07-25T00:00:00Z", "updated_at": "2026-07-25T00:00:00Z",
	},
	{
		"id": "7a70eab8-cfcc-5620-aa0c-3c764edd7d45", "code": "TODO_RIESGO_HOGAR",
		"name": "Todo riesgo hogar",
		"description": "Protección del hogar y sus contenidos ante distintos riesgos.",
		"category": "patrimonio", "active": true, "base_price": 32000.0,
		"coverages": []Coverage{
			{Key: "hogar", Label: "Hogar", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "contenido", Label: "Contenido", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "proteccion_patrimonial", Label: "Proteccion patrimonial", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "asistencia_domiciliaria", Label: "Asistencia domiciliaria (plomería, cerrajería)", Included: false, PriceDelta: 5000, Source: "estimacion_demo"},
			{Key: "contenido_electronico", Label: "Contenido electrónico y tecnología", Included: false, PriceDelta: 7000, Source: "estimacion_demo"},
		},
		"metadata_json": map[string]interface{}{
			"segmento": "patrimonio", "subsegmento": "hogar",
			"modalidad": "individual", "alianza": "aseguradoras_del_pais",
			"beneficios": []string{"respaldo_del_hogar"},
			"canales": []string{"portafolio_patrimonial"},
			"fuentes": []string{"https://ayuda.colsubsidio.com/que-seguros-asistencias-ofrece-colsubsidio"},
			"price_source": "estimación de demo — Colsubsidio no publica primas (ver condiciones_no_publicadas en sourceapi.json)",
			"condiciones_no_publicadas": []string{"deducibles", "valor_asegurado", "exclusiones", "riesgos_especificos"},
		},
		"created_at": "2026-07-25T00:00:00Z", "updated_at": "2026-07-25T00:00:00Z",
	},
	{
		"id": "1dfba435-9a86-55b7-bf38-eaf351b0ed1c", "code": "BICICLETAS",
		"name": "Bicicletas",
		"description": "Cobertura patrimonial para bicicletas.",
		"category": "patrimonio", "active": true, "base_price": 14000.0,
		"coverages": []Coverage{
			{Key: "bicicletas", Label: "Bicicletas", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "asistencia_domiciliaria", Label: "Asistencia domiciliaria (plomería, cerrajería)", Included: false, PriceDelta: 5000, Source: "estimacion_demo"},
			{Key: "contenido_electronico", Label: "Contenido electrónico y tecnología", Included: false, PriceDelta: 7000, Source: "estimacion_demo"},
		},
		"metadata_json": map[string]interface{}{
			"segmento": "patrimonio", "subsegmento": "movilidad",
			"modalidad": "individual", "alianza": "aseguradoras_del_pais",
			"beneficios": []string{"proteccion_de_movilidad"},
			"canales": []string{"portafolio_patrimonial"},
			"fuentes": []string{"https://ayuda.colsubsidio.com/que-seguros-asistencias-ofrece-colsubsidio"},
			"price_source": "estimación de demo — Colsubsidio no publica primas (ver condiciones_no_publicadas en sourceapi.json)",
			"condiciones_no_publicadas": []string{"tipos_de_bici", "valor_maximo", "robo", "accidentes", "exclusiones"},
		},
		"created_at": "2026-07-25T00:00:00Z", "updated_at": "2026-07-25T00:00:00Z",
	},
	{
		"id": "0e98938c-21d9-5813-99f8-42da8a861ab3", "code": "ARRENDAMIENTO",
		"name": "Arrendamiento",
		"description": "Seguro vinculado a contratos de arriendo.",
		"category": "patrimonio", "active": true, "base_price": 39000.0,
		"coverages": []Coverage{
			{Key: "arrendamiento", Label: "Canon de arrendamiento", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "asistencia_domiciliaria", Label: "Asistencia domiciliaria (plomería, cerrajería)", Included: false, PriceDelta: 5000, Source: "estimacion_demo"},
			{Key: "contenido_electronico", Label: "Contenido electrónico y tecnología", Included: false, PriceDelta: 7000, Source: "estimacion_demo"},
		},
		"metadata_json": map[string]interface{}{
			"segmento": "patrimonio", "subsegmento": "contratos",
			"modalidad": "individual", "alianza": "aseguradoras_del_pais",
			"beneficios": []string{"respaldo_contractual"},
			"canales": []string{"portafolio_patrimonial"},
			"fuentes": []string{"https://ayuda.colsubsidio.com/que-seguros-asistencias-ofrece-colsubsidio"},
			"price_source": "estimación de demo — Colsubsidio no publica primas (ver condiciones_no_publicadas en sourceapi.json)",
			"condiciones_no_publicadas": []string{"canon_cubierto", "garantia", "exclusiones", "vigencia"},
		},
		"created_at": "2026-07-25T00:00:00Z", "updated_at": "2026-07-25T00:00:00Z",
	},
	{
		"id": "3393b8a7-8ecd-5225-9ca8-db7213ad8027", "code": "ASISTENCIA_M_DICA_FAMILIAR",
		"name": "Asistencia médica familiar",
		"description": "Servicio de asistencia médica familiar con acceso a médicos a domicilio y orientación en salud.",
		"category": "asistencias", "active": true, "base_price": 19000.0,
		"coverages": []Coverage{
			{Key: "médicos_a_domicilio", Label: "Médicos a domicilio", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "orientacion_medica", Label: "Orientacion medica", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "atencion_24_7", Label: "Atencion 24 7", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "cobertura_ampliada", Label: "Cobertura ampliada 24/7 sin límite de eventos", Included: false, PriceDelta: 3000, Source: "estimacion_demo"},
		},
		"metadata_json": map[string]interface{}{
			"segmento": "asistencias", "subsegmento": "salud",
			"modalidad": "familiar", "alianza": "aseguradoras_del_pais",
			"beneficios": []string{"atencion_inmediata", "comodidad"},
			"canales": []string{"pagina_web", "asistencias"},
			"fuentes": []string{"https://ayuda.colsubsidio.com/que-seguros-asistencias-ofrece-colsubsidio", "https://www.colsubsidio.com/seguros/familiares"},
			"price_source": "estimación de demo — Colsubsidio no publica primas (ver condiciones_no_publicadas en sourceapi.json)",
			"condiciones_no_publicadas": []string{"cobertura_geografica_completa", "tiempos_de_respuesta", "limites_por_evento"},
		},
		"created_at": "2026-07-25T00:00:00Z", "updated_at": "2026-07-25T00:00:00Z",
	},
	{
		"id": "c0ddab4b-79e7-535f-9b5a-50752e175446", "code": "ASISTENCIA_MASCOTAS",
		"name": "Asistencia mascotas",
		"description": "Asistencia enfocada en el cuidado y apoyo para mascotas.",
		"category": "asistencias", "active": true, "base_price": 12000.0,
		"coverages": []Coverage{
			{Key: "mascotas", Label: "Mascotas", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "cobertura_ampliada", Label: "Cobertura ampliada 24/7 sin límite de eventos", Included: false, PriceDelta: 3000, Source: "estimacion_demo"},
		},
		"metadata_json": map[string]interface{}{
			"segmento": "asistencias", "subsegmento": "mascotas",
			"modalidad": "individual_familiar", "alianza": "aseguradoras_del_pais",
			"beneficios": []string{"cuidado_integral"},
			"canales": []string{"asistencias"},
			"fuentes": []string{"https://ayuda.colsubsidio.com/que-seguros-asistencias-ofrece-colsubsidio"},
			"price_source": "estimación de demo — Colsubsidio no publica primas (ver condiciones_no_publicadas en sourceapi.json)",
			"condiciones_no_publicadas": []string{"servicios_incluidos", "limites", "exclusiones"},
		},
		"created_at": "2026-07-25T00:00:00Z", "updated_at": "2026-07-25T00:00:00Z",
	},
	{
		"id": "f6a78143-22ca-54ec-92f0-2a910c70d87e", "code": "ASISTENCIA_JUR_DICA",
		"name": "Asistencia jurídica",
		"description": "Servicio de apoyo legal o jurídico dentro del portafolio de asistencias.",
		"category": "asistencias", "active": true, "base_price": 11000.0,
		"coverages": []Coverage{
			{Key: "asistencia_legal", Label: "Asistencia legal", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "asistencia_juridica", Label: "Asistencia juridica", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "cobertura_ampliada", Label: "Cobertura ampliada 24/7 sin límite de eventos", Included: false, PriceDelta: 3000, Source: "estimacion_demo"},
		},
		"metadata_json": map[string]interface{}{
			"segmento": "asistencias", "subsegmento": "legal",
			"modalidad": "individual_familiar", "alianza": "aseguradoras_del_pais",
			"beneficios": []string{"orientacion_legal"},
			"canales": []string{"asistencias"},
			"fuentes": []string{"https://ayuda.colsubsidio.com/que-seguros-asistencias-ofrece-colsubsidio"},
			"price_source": "estimación de demo — Colsubsidio no publica primas (ver condiciones_no_publicadas en sourceapi.json)",
			"condiciones_no_publicadas": []string{"alcance", "topes", "horarios", "casos_cubiertos"},
		},
		"created_at": "2026-07-25T00:00:00Z", "updated_at": "2026-07-25T00:00:00Z",
	},
	{
		"id": "574b04a0-9530-5ade-a818-aec563b17acc", "code": "SEGURO_DE_VIDA_DEUDOR",
		"name": "Seguro de vida deudor",
		"description": "Protege la deuda del titular en caso de fallecimiento o incapacidad.",
		"category": "credito", "active": true, "base_price": 13000.0,
		"coverages": []Coverage{
			{Key: "fallecimiento", Label: "Fallecimiento", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "incapacidad_total_o_permanente", Label: "Incapacidad total o permanente", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "respaldo_deuda", Label: "Respaldo deuda", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "proteccion_extendida", Label: "Protección extendida por 12 meses adicionales", Included: false, PriceDelta: 5000, Source: "estimacion_demo"},
		},
		"metadata_json": map[string]interface{}{
			"segmento": "credito", "subsegmento": "proteccion_obligaciones",
			"modalidad": "asociado_a_credito", "alianza": "aseguradoras_del_pais",
			"beneficios": []string{"mantener_obligaciones_al_dia"},
			"canales": []string{"productos_de_credito", "carta_tarifas"},
			"fuentes": []string{"https://cms.colsubsidio.com/sites/default/files/Documentos/colsubsidio/2026/cupo-credito-colsubsidio-carta-tarifas.pdf"},
			"price_source": "estimación de demo — Colsubsidio no publica primas (ver condiciones_no_publicadas en sourceapi.json)",
			"condiciones_no_publicadas": []string{"suma_asegurada", "condiciones_de_endoso", "exclusiones"},
		},
		"created_at": "2026-07-25T00:00:00Z", "updated_at": "2026-07-25T00:00:00Z",
	},
	{
		"id": "fa6a2c6b-0432-55f1-949b-9fa15050344e", "code": "SEGURO_DE_DESEMPLEO",
		"name": "Seguro de desempleo",
		"description": "Cubre cuotas del crédito ante desempleo involuntario o incapacidad temporal.",
		"category": "credito", "active": true, "base_price": 17000.0,
		"coverages": []Coverage{
			{Key: "desempleo_involuntario", Label: "Desempleo involuntario", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "incapacidad_temporal", Label: "Incapacidad temporal", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "hasta_9_cuotas", Label: "Hasta 9 cuotas", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "proteccion_extendida", Label: "Protección extendida por 12 meses adicionales", Included: false, PriceDelta: 5000, Source: "estimacion_demo"},
		},
		"metadata_json": map[string]interface{}{
			"segmento": "credito", "subsegmento": "proteccion_ingresos",
			"modalidad": "asociado_a_credito", "alianza": "aseguradoras_del_pais",
			"beneficios": []string{"evitar_mora", "proteccion_financiera"},
			"canales": []string{"productos_de_credito", "carta_tarifas"},
			"fuentes": []string{"https://cms.colsubsidio.com/sites/default/files/Documentos/colsubsidio/2026/cupo-credito-colsubsidio-carta-tarifas.pdf"},
			"price_source": "estimación de demo — Colsubsidio no publica primas (ver condiciones_no_publicadas en sourceapi.json)",
			"condiciones_no_publicadas": []string{"periodo_de_espera", "requisitos_laborales", "exclusiones"},
		},
		"created_at": "2026-07-25T00:00:00Z", "updated_at": "2026-07-25T00:00:00Z",
	},
	{
		"id": "1adbbc1d-b1fa-5c9f-a7f0-d6c5c3c9a494", "code": "SEGURO_DE_INCENDIO",
		"name": "Seguro de incendio",
		"description": "Protege el patrimonio frente a incendio y fenómenos naturales.",
		"category": "credito", "active": true, "base_price": 23000.0,
		"coverages": []Coverage{
			{Key: "incendio", Label: "Incendio", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "fenomenos_naturales", Label: "Fenomenos naturales", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "proteccion_extendida", Label: "Protección extendida por 12 meses adicionales", Included: false, PriceDelta: 5000, Source: "estimacion_demo"},
		},
		"metadata_json": map[string]interface{}{
			"segmento": "credito", "subsegmento": "patrimonio_vinculado_a_credito",
			"modalidad": "asociado_a_credito", "alianza": "aseguradoras_del_pais",
			"beneficios": []string{"proteccion_patrimonial"},
			"canales": []string{"productos_de_credito"},
			"fuentes": []string{"https://cms.colsubsidio.com/sites/default/files/Documentos/colsubsidio/2026/cupo-credito-colsubsidio-carta-tarifas.pdf"},
			"price_source": "estimación de demo — Colsubsidio no publica primas (ver condiciones_no_publicadas en sourceapi.json)",
			"condiciones_no_publicadas": []string{"valor_asegurado", "deducibles", "exclusiones"},
		},
		"created_at": "2026-07-25T00:00:00Z", "updated_at": "2026-07-25T00:00:00Z",
	},
	{
		"id": "94c2722c-9e2b-5f27-85f2-c739f1350adb", "code": "ASISTENCIA_M_DICA_EN_VIAJES",
		"name": "Asistencia médica en viajes",
		"description": "Asistencia 24/7 con cobertura internacional y apoyo en gastos médicos durante viajes.",
		"category": "credito", "active": true, "base_price": 26000.0,
		"coverages": []Coverage{
			{Key: "atencion_24_7", Label: "Atencion 24 7", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "cobertura_internacional", Label: "Cobertura internacional", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "gastos_medicos", Label: "Gastos médicos", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "proteccion_extendida", Label: "Protección extendida por 12 meses adicionales", Included: false, PriceDelta: 5000, Source: "estimacion_demo"},
		},
		"metadata_json": map[string]interface{}{
			"segmento": "credito", "subsegmento": "viajes",
			"modalidad": "individual", "alianza": "aseguradoras_del_pais",
			"beneficios": []string{"tranquilidad_en_viajes"},
			"canales": []string{"productos_de_credito"},
			"fuentes": []string{"https://cms.colsubsidio.com/sites/default/files/Documentos/colsubsidio/2026/cupo-credito-colsubsidio-carta-tarifas.pdf"},
			"price_source": "estimación de demo — Colsubsidio no publica primas (ver condiciones_no_publicadas en sourceapi.json)",
			"condiciones_no_publicadas": []string{"limites_por_evento", "paises_cubiertos", "exclusiones"},
		},
		"created_at": "2026-07-25T00:00:00Z", "updated_at": "2026-07-25T00:00:00Z",
	},
	{
		"id": "3167de57-d2db-5a85-883e-a2b3b98ce303", "code": "SEGUROS_COLECTIVOS_PARA_EMPRESAS",
		"name": "Seguros colectivos para empresas",
		"description": "Soluciones colectivas para empresas con pólizas de salud, exequiales y otras coberturas.",
		"category": "empresas", "active": true, "base_price": 240000.0,
		"coverages": []Coverage{
			{Key: "salud", Label: "Atención en salud", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "exequial", Label: "Exequial", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "coberturas_colectivas", Label: "Coberturas colectivas", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "cobertura_colectiva_ampliada", Label: "Ampliación de cobertura al grupo familiar", Included: false, PriceDelta: 12000, Source: "estimacion_demo"},
		},
		"metadata_json": map[string]interface{}{
			"segmento": "empresas", "subsegmento": "bienestar_corporativo",
			"modalidad": "colectivo", "alianza": "aseguradoras_del_pais",
			"beneficios": []string{"beneficios_personalizados", "seguridad_integral"},
			"canales": []string{"portal_empresas", "asesoria_comercial"},
			"fuentes": []string{"https://www.colsubsidio.com/empresas/bienestar/seguros"},
			"price_source": "estimación de demo — Colsubsidio no publica primas (ver condiciones_no_publicadas en sourceapi.json)",
			"condiciones_no_publicadas": []string{"numero_minimo_de_asegurados", "topes", "exclusiones", "condiciones_de_emision"},
		},
		"created_at": "2026-07-25T00:00:00Z", "updated_at": "2026-07-25T00:00:00Z",
	},
	{
		"id": "7155b64d-b5bf-56bf-a357-dcdbd7435d55", "code": "P_LIZA_COLECTIVA_DE_SALUD_PARA_EMPRESAS",
		"name": "Póliza colectiva de salud para empresas",
		"description": "Cobertura médica colectiva con acceso preferencial a clínicas, especialistas y servicios para empleados y familias.",
		"category": "empresas", "active": true, "base_price": 310000.0,
		"coverages": []Coverage{
			{Key: "salud", Label: "Atención en salud", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "acceso_preferencial", Label: "Acceso preferencial", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "especialistas", Label: "Especialistas", Included: true, PriceDelta: 0, Source: "portafolio_publicado"},
			{Key: "cobertura_colectiva_ampliada", Label: "Ampliación de cobertura al grupo familiar", Included: false, PriceDelta: 12000, Source: "estimacion_demo"},
		},
		"metadata_json": map[string]interface{}{
			"segmento": "empresas", "subsegmento": "salud",
			"modalidad": "colectivo", "alianza": "aseguradoras_del_pais",
			"beneficios": []string{"bienestar_del_equipo"},
			"canales": []string{"portal_empresas"},
			"fuentes": []string{"https://www.colsubsidio.com/empresas/bienestar/seguros/colectivo-salud"},
			"price_source": "estimación de demo — Colsubsidio no publica primas (ver condiciones_no_publicadas en sourceapi.json)",
			"condiciones_no_publicadas": []string{"carencias", "topes", "red_medica_exacta", "copagos"},
		},
		"created_at": "2026-07-25T00:00:00Z", "updated_at": "2026-07-25T00:00:00Z",
	},
}

// productIDs expone los identificadores por clave del portafolio, para que las
// reglas se escriban contra un nombre legible y no contra un UUID suelto.
var productIDs = map[string]string{
	"seguro-vida": "ef4cc0ae-64af-5c70-a9f7-bfbf7e09b650",
	"seguro-vida-ahorro": "31beb920-0fed-51ce-b2df-b84a48e19600",
	"accidentes-personales": "cd2965eb-1d0b-53a1-a20e-2af4ebf87ac8",
	"renta-hospitalizacion": "e61a75d2-d95a-5566-98ce-f65046a96ad5",
	"diagnostico-cancer": "7bfc424a-00ac-59b1-bdd3-d0b4fe7afa39",
	"poliza-salud": "78de9b51-29d9-5506-ba6d-d74a4763e3d9",
	"exequial-familiar": "a80efc0f-3b48-5e16-a295-c89883ce362d",
	"seguro-mascotas": "b25c56e5-b406-5609-be1f-d6ea6eda04b2",
	"autos-motos": "51e10984-578e-59fd-b68c-d8e26e9bc42a",
	"hogar": "7a70eab8-cfcc-5620-aa0c-3c764edd7d45",
	"bicicletas": "1dfba435-9a86-55b7-bf38-eaf351b0ed1c",
	"arrendamiento": "0e98938c-21d9-5813-99f8-42da8a861ab3",
	"asistencia-medica-familiar": "3393b8a7-8ecd-5225-9ca8-db7213ad8027",
	"asistencia-mascotas": "c0ddab4b-79e7-535f-9b5a-50752e175446",
	"asistencia-juridica": "f6a78143-22ca-54ec-92f0-2a910c70d87e",
	"seguro-vida-deudor": "574b04a0-9530-5ade-a818-aec563b17acc",
	"seguro-desempleo": "fa6a2c6b-0432-55f1-949b-9fa15050344e",
	"seguro-incendio": "1adbbc1d-b1fa-5c9f-a7f0-d6c5c3c9a494",
	"asistencia-medica-viajes": "94c2722c-9e2b-5f27-85f2-c739f1350adb",
	"empresas-colectivo": "3167de57-d2db-5a85-883e-a2b3b98ce303",
	"empresas-salud-colectiva": "7155b64d-b5bf-56bf-a357-dcdbd7435d55",
}

